# Generated by Django 5.2.11 on 2026-02-24 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_exerciseresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='Plik PDF'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='type',
            field=models.CharField(choices=[('grammar', 'baza wiedzy - teoria'), ('exercise', 'ćwiczenia'), ('reading', 'czytanie'), ('writing', 'pisanie')], max_length=20),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nazwa zadania')),
                ('url_link', models.URLField(verbose_name='Link do zadania')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='content.lesson', verbose_name='Do jakiego tematu to należy?')),
            ],
        ),
    ]
