# Generated by Django 5.2.11 on 2026-02-24 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_lesson_pdf_file_alter_lesson_type_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500, verbose_name='Treść pytania (np. I ___ a cat.)')),
                ('option_a', models.CharField(max_length=200, verbose_name='Odpowiedź A')),
                ('option_b', models.CharField(max_length=200, verbose_name='Odpowiedź B')),
                ('option_c', models.CharField(max_length=200, verbose_name='Odpowiedź C')),
                ('correct_answer', models.CharField(choices=[('A', 'Odpowiedź A'), ('B', 'Odpowiedź B'), ('C', 'Odpowiedź C')], max_length=1, verbose_name='Poprawna odpowiedź')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.lesson', verbose_name='Lekcja')),
            ],
        ),
        migrations.CreateModel(
            name='TextExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.CharField(default='Wpisz odpowiednią formę czasownika:', max_length=200, verbose_name='Polecenie')),
                ('question_text', models.CharField(max_length=500, verbose_name="Treść zadania (np. 'She ___ (go) to school.')")),
                ('correct_answer', models.CharField(max_length=200, verbose_name="Poprawna odpowiedź (np. 'goes')")),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_exercises', to='content.lesson', verbose_name='Lekcja')),
            ],
        ),
    ]
