# Generated by Django 5.2.11 on 2026-02-24 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_quizquestion_textexercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='question',
        ),
        migrations.AddField(
            model_name='exercise',
            name='instruction',
            field=models.CharField(default='Uzupełnij luki', max_length=200, verbose_name='Polecenie do zadania (np. Uzupełnij luki w zdaniach twierdzących)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='content.lesson', verbose_name='Lekcja'),
        ),
        migrations.CreateModel(
            name='ExerciseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500, verbose_name="Zdanie z luką (np. 'She ___ (go) to school.')")),
                ('correct_answer', models.CharField(max_length=200, verbose_name="Poprawna odpowiedź (np. 'goes')")),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.exercise', verbose_name='Do jakiego zadania to należy?')),
            ],
        ),
        migrations.DeleteModel(
            name='TextExercise',
        ),
    ]
